### ISSUE TITLE
Replace Python Console Apps with C++ Console Apps.

### ISSUE THREAD

**Issue by AraHaan** [AraHaan/Els_kom_new#18]
The Python console Apps are Good but are not good with my DLL that should do the Crypto++ work when Alg 3 is Added in.

Things to Consider:
1: Args must be the same as the Python Ones to avoid breaking the bat files.
2: Algorithm 3 Support.
3: Smaller Files than the Python PyInstaller Compiled ones.
4. Faster
5. No waste of disc space every time it is used to unpack or pack things unlike pyintaller compiled ones that would waste a ton of space to use on every execution.

**Comment by AraHaan** [comment]
@gvanrossum mind helping me contact the creator of the zlib module? I would like to make an entirely c++ version of the python zlib module so that way it makes all the things this project needs much better. Currently I need the zlib from python ported to c++ to help me gain the exact same functionality and everything from python without using the python core to import the zlib module just to get the proper data from the compress / decompress functions to write to a file using fstream in c++.  So yeah the code to it would have to be separated from the python stuff to work. You might see what I mean by this by looking in this folder in this repository: https://github.com/AraHaan/Els_kom_new/blob/master/Els_kom_Generic_Unpacker/src/

**Comment by gvanrossum** [comment]
I don't know who that was. But I don't understand why you want Python's zlib module translated to C++ -- can't you call the C code from zlib (found here: https://www.zlib.net/) directly? (TBH most of your project is a mystery to me -- I seem to be utterly lacking context to even understand what you mean by Python Console Apps, for example.)

**Comment by AraHaan** [comment]
Well, for starters the memory compression on Python's versions is working great. And another part to it is that I do not know how to use the c version of zlib itself. Only the python one. This is why I need it to use such directly in my C++ code. I do plan to do something with crypto++ later too.
Basically what I need is unlike passing multiple parameters to compress or decompress an file's data that is read, I want to use the python way and get away with only needing to pass in 1 and that is the data itself.

Like in Python I like being able to do (Minified code):

```py
import zlib

somefile = open('./somefilehere.txt', 'rb')
somedata = somefile.read()
zlib.compress(somedata)
```

In C it looks to be more complicated than this. This is why I need to port it to C++ so I can get away with calling an compress and decompression just like how someone can in python.

**Comment by gvanrossum** [comment]
Well, you're going to have to figure out how call zlib from C++ yourself. Study the source code for Python's zlib. It's all in Modules/zlibmodule.c in the cpython repo. Good luck!

**Comment by AraHaan** [comment]
Closing this for now as C++ was being a pain before. I will see what I can do about the encryption and see if I have working xor keys.
